### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by JulienGrv**
So now everything is perfect :)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by JulienGrv** [comment]
numpy is missing on travis, should I add it?

**Comment by JulienGrv** [comment]
> numpy is missing in the travis config, should I add it?

I tested adding numpy and scipy but it didn't work so I removed them

**Comment by JulienGrv** [comment]
Ok I did some improvements to the CI but there is still 1 test that fails, I will continue next week but you can already merge since it improves and fixes issues in the master branch.

**Comment by christoph2** [comment]
Hi Julien, 

Thank you for your work. 
Unfortunately there are some merge conflicts, I'll try to fix them.

**Comment by christoph2** [comment]
Hmm,  for unknown reasons Github seemed confused - - following the the command line instructions I was able to merge without any problems.

**Comment by christoph2** [comment]
Again, thank you for your hard work. 👍  -- I've just added a CONTRIBUTORS file 😄

**Pull request merged**
